event-master/src/Entity/Employes.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EmployesRepository")
 */
class Employes
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="date")
     */
    private $DateDebut;

    /**
     * @ORM\Column(type="integer")
     */
    private $NbMission;

    /**
     * @ORM\Column(type="integer")
     */
    private $NbMissionNonPayees;

    /**
     * @ORM\Column(type="integer")
     */
    private $SalaireParPrestation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $TypePost;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Prestation", mappedBy="EmployesAssignes")
     */
    private $PrestationsAssignees;

    public function __construct()
    {
        $this->PrestationsAssignees = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->DateDebut;
    }

    public function setDateDebut(\DateTimeInterface $DateDebut): self
    {
        $this->DateDebut = $DateDebut;

        return $this;
    }

    public function getNbMission(): ?int
    {
        return $this->NbMission;
    }

    public function setNbMission(int $NbMission): self
    {
        $this->NbMission = $NbMission;

        return $this;
    }

    public function getNbMissionNonPayees(): ?int
    {
        return $this->NbMissionNonPayees;
    }

    public function setNbMissionNonPayees(int $NbMissionNonPayees): self
    {
        $this->NbMissionNonPayees = $NbMissionNonPayees;

        return $this;
    }

    public function getSalaireParPrestation(): ?int
    {
        return $this->SalaireParPrestation;
    }

    public function setSalaireParPrestation(int $SalaireParPrestation): self
    {
        $this->SalaireParPrestation = $SalaireParPrestation;

        return $this;
    }

    public function getTypePost(): ?string
    {
        return $this->TypePost;
    }

    public function setTypePost(string $TypePost): self
    {
        $this->TypePost = $TypePost;

        return $this;
    }

    /**
     * @return Collection|Prestation[]
     */
    public function getPrestationsAssignees(): Collection
    {
        return $this->PrestationsAssignees;
    }

    public function addPrestationsAssignee(Prestation $prestationsAssignee): self
    {
        if (!$this->PrestationsAssignees->contains($prestationsAssignee)) {
            $this->PrestationsAssignees[] = $prestationsAssignee;
            $prestationsAssignee->addEmployesAssigne($this);
        }

        return $this;
    }

    public function removePrestationsAssignee(Prestation $prestationsAssignee): self
    {
        if ($this->PrestationsAssignees->contains($prestationsAssignee)) {
            $this->PrestationsAssignees->removeElement($prestationsAssignee);
            $prestationsAssignee->removeEmployesAssigne($this);
        }

        return $this;
    }
}

event-master/src/Controller/EmployesController.php
<?php

namespace App\Controller;


use App\Entity\Employes;
use App\Entity\Prestation;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class EmployesController extends AbstractController
{
    /**
     * @Route("/admin/employes/new", name="create_employe")
     * @Route("/admin/employes/{id}/edit",name="edit_employe")
     */
    public function create(Request $request ,EntityManagerInterface $manager,Employes $employe=null) {
        $modified = true;
        if(!$employe){
            $employe = new Employes();
            $modified = false;
        }
        
        $formEmploye = $this->createFormBuilder($employe)
                            ->add('Nom',TextType::class,[
                                'attr'=> [
                                    'placeholder' => 'Nom de l\'emplyé ...'
                                ]
                            ])
                            ->add('Prenom',TextType::class,[
                                'attr'=> [
                                    'placeholder' => 'Prénom de l\'emplyé ...'
                                ]
                            ])
                            ->add('typePost',  ChoiceType::class, [
                                'choices'  => [
                                    'Employé polyvalant' => 'Employé polyvalant',
                                    'Gérant' => 'Gérant',
                                    'DJ' => 'DJ'],
                            ])
                            -> add('salaireParPrestation',IntegerType::class,['attr' => [
                                'placeholder'=> 'salaire par prestation ...']])
                            ->getForm();
        
        $formEmploye->handleRequest($request);
        if($formEmploye->isSubmitted() && $formEmploye->isValid()){    
            if(!$modified){
                $employe->setDateDebut(new \DateTime('now'));
            }
            
            $employe->setNbMission(0)
            ->setNbMissionNonPayees(0);
            $manager->persist($employe);
            $manager->flush();
            if ($modified){
                $this->addFlash('success','l\'employes '.$employe->getNom().' a bien été modifié' );
            }else{
                $this->addFlash('success','l\'employes '.$employe->getNom().' a bien été crée' );
            }
            return $this->redirectToRoute('show_employes');
        }
                            return $this->render('Employes/new.html.twig',['formEmploye' => $formEmploye->createView()]);
    }


   
        /**
     *  @Route("/admin/employes", name="show_employes")
     */
    public function employes(){
        $repo = $this->getDoctrine()->getRepository(Employes::class);
        $employes = $repo->findBy([],['NbMission' => 'DESC']);
        return $this->render('employes/index.html.twig',[
            'controller_name' => 'EmployesController',
            'employes' => $employes
        ]);
    }

    /**
     * @Route("/admin/employes/{id}/delete", name="delete_employe", methods="DELETE")
     */
    public function deleteemploye(EntityManagerInterface $manager,Employes $employe){
        $manager->remove($employe);
        $manager->flush();
        $this->addFlash('success','l\'employé '.$employe->getNom().' a bien été supprimé' );
        return $this->redirectToRoute('show_employes');
    }


    public function employe(Request $request){
        return $this->getDoctrine()->getRepository(Employes::class)->find($request->request->get('ide'));
    }
 


    }

event-master/templates/employes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EmployesController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
<h1> Presentation des Employes </h1>

    {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}

    <table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Nom</th>
      <th scope="col">Prenom </th>
      <th scope="col">Date de début </th>
      <th scope="col">nombre de missions</th>
      <th scope="col">Nombre de missions non payés </th>
      <th scope="col">Poste occupé</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  {% for employe in employes %}
    <tr class="table-light">
     
      <td>{{employe.nom}}</td>
      <td>{{employe.prenom}}</td>
      <td>{{employe.dateDebut | date('Y/m/d')}}</td>
      <td>{{employe.NbMission}}</td>
      <td>{{employe.NbMissionNonPayees}}</td>
      <td>{{employe.TypePost}}</td>
      <td><button type="button" class="btn btn-secondary disabled"><a href={{path('edit_employe', {'id': employe.id})}} style="color:white">modifier </a> </button></td>
      <td>
       <form method="POST" action="{{path('delete_employe', {'id': employe.id})}}" onsubmit="return confirm('etes vous sur de vouloir supprimer ?')">
            <input type="hidden" name="_method" value="DELETE">
            <button class="btn btn-danger">supprimer</button>
        </form>
      




    
      
      </td>
      
    </tr>
    {% endfor %}
    </tbody>
    </table>
{% endblock %}

event-master/templates/employes/new.html.twig
{% extends 'base.html.twig' %}
{% form_theme formEmploye 'bootstrap_4_layout.html.twig'%}


{% block body %}
<h1> ajout employé </h1>
    {{form_start(formEmploye)}}
    {{ form_widget(formEmploye) }}
    <div class="form-group"><button type="submit" class="btn btn-primary">Ajouter employé </button></div>
    {{ form_end(formEmploye) }}
{% endblock %}