event-master/src/Entity/MesPrestationInterval.php
<?php

namespace App\Entity;

use App\Repository\MesPrestationIntervalRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MesPrestationIntervalRepository::class)
 */
class MesPrestationInterval
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $IntervalMin;

    /**
     * @ORM\Column(type="integer")
     */
    private $IntervalMax;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantite;

    /**
     * @ORM\Column(type="integer")
     */
    private $prixUnitaire;

    /**
     * @ORM\Column(type="integer")
     */
    private $tauxInterval;

    /**
     * @ORM\Column(type="integer")
     */
    private $tauxErreur;

    /**
     * @ORM\ManyToOne(targetEntity=MesPrestation::class, inversedBy="mesPrestationIntervals",cascade={"remove"})
     */
    private $MaPrestation;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantiteNonMixte;

    /**
     * @ORM\Column(type="integer")
     */
    private $prixUnitaireNonMixte;

    /**
     * @ORM\Column(type="integer")
     */
    private $tauxIntervalNonMixte;

    /**
     * @ORM\Column(type="integer")
     */
    private $tauxErreurNonMixte;

   

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIntervalMin(): ?int
    {
        return $this->IntervalMin;
    }

    public function setIntervalMin(int $IntervalMin): self
    {
        $this->IntervalMin = $IntervalMin;

        return $this;
    }

    public function getIntervalMax(): ?int
    {
        return $this->IntervalMax;
    }

    public function setIntervalMax(int $IntervalMax): self
    {
        $this->IntervalMax = $IntervalMax;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getPrixUnitaire(): ?int
    {
        return $this->prixUnitaire;
    }

    public function setPrixUnitaire(int $prixUnitaire): self
    {
        $this->prixUnitaire = $prixUnitaire;

        return $this;
    }

    public function getTauxInterval(): ?int
    {
        return $this->tauxInterval;
    }

    public function setTauxInterval(int $tauxInterval): self
    {
        $this->tauxInterval = $tauxInterval;

        return $this;
    }

    public function getTauxErreur(): ?int
    {
        return $this->tauxErreur;
    }

    public function setTauxErreur(int $tauxErreur): self
    {
        $this->tauxErreur = $tauxErreur;

        return $this;
    }

    public function getMaPrestation(): ?MesPrestation
    {
        return $this->MaPrestation;
    }

    public function setMaPrestation(?MesPrestation $MaPrestation): self
    {
        $this->MaPrestation = $MaPrestation;

        return $this;
    }

    public function getQuantiteNonMixte(): ?int
    {
        return $this->quantiteNonMixte;
    }

    public function setQuantiteNonMixte(int $quantiteNonMixte): self
    {
        $this->quantiteNonMixte = $quantiteNonMixte;

        return $this;
    }

    public function getPrixUnitaireNonMixte(): ?int
    {
        return $this->prixUnitaireNonMixte;
    }

    public function setPrixUnitaireNonMixte(int $prixUnitaireNonMixte): self
    {
        $this->prixUnitaireNonMixte = $prixUnitaireNonMixte;

        return $this;
    }

    public function getTauxIntervalNonMixte(): ?int
    {
        return $this->tauxIntervalNonMixte;
    }

    public function setTauxIntervalNonMixte(int $tauxIntervalNonMixte): self
    {
        $this->tauxIntervalNonMixte = $tauxIntervalNonMixte;

        return $this;
    }

    public function getTauxErreurNonMixte(): ?int
    {
        return $this->tauxErreurNonMixte;
    }

    public function setTauxErreurNonMixte(int $tauxErreurNonMixte): self
    {
        $this->tauxErreurNonMixte = $tauxErreurNonMixte;

        return $this;
    }

}

event-master/src/Form/MesPrestationType.php
<?php

namespace App\Form;

use App\Entity\MesPrestation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;

class MesPrestationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nomPrestation')
            ->add('nombreEmployes')
            ->add('prix')
            ->add('DependNbInvites')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => MesPrestation::class,
        ]);
    }
}

event-master/src/Controller/MesPrestationController.php
<?php

namespace App\Controller;

use Error;
use App\Entity\MesPrestation;
use App\Form\MesPrestationType;
use Doctrine\DBAL\DBALException;
use App\Entity\MesPrestationInterval;
use Doctrine\ORM\EntityManagerInterface;
use phpDocumentor\Reflection\Types\Boolean;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MesPrestationController extends AbstractController
{
    /**
     * @Route("/admin/mes_prestation/new",name="new_ma_prestation")
     * @Route("/admin/mes_prestation/{id}/edit",name="edit_ma_prestation")
     */
    public function add(Request $request ,EntityManagerInterface $manager,MesPrestation $maPrestation=null)
    { 
        $modified = false;
        if ($maPrestation != null){
            $modified = true;
        }
        else{
        $maPrestation = new MesPrestation();
        }
      $form = $this->createForm(MesPrestationType::class,$maPrestation);
      $form->handleRequest($request);
      if($form->isSubmitted() && $form->isValid()){
          if ($maPrestation->getDependNbInvites() ==true){
            $maPrestation->setDependNbInvites(1);

          }else{
            $maPrestation->setDependNbInvites(0);
          }
          try{
        $manager->persist($maPrestation);
        $manager->flush();
        if($maPrestation->getDependNbInvites()){
            return $this->addInterval($maPrestation);
        }else{
        
        return $this->redirectToRoute('show_mes_prestation');
        }
    }
    catch  (DBALException  $e){
        $this->addFlash('warning','Une erreur c\'est produite, merci de verifier les informations renseignées' );
        return $this->redirectToRoute('new_ma_prestation');
    }
        
    }
    if($modified){

        $this->addFlash('success','Votre modification a bien été enregistée.' );
    }else{
        $this->addFlash('success','Votre prestation a bien été enregistée.' );

    }
      return $this->render('mes_prestation/new.html.twig', [
        'form' => $form->createView(),'modified' => $modified]);
    }

    public function addInterval(MesPrestation $maPrestation ){
        return $this->render('mes_prestation/add_interval.html.twig',[
            'maPrestation' => $maPrestation
        ]);
    }
    /**
     * @Route("/admin/mes_prestation/putAddedInterval",name="putAddedInterval")
     */
    public function putAddedInterval(Request $request,EntityManagerInterface $manager ){
// on recupere notre prestation 

        $repo = $this->getDoctrine()->getRepository(MesPrestation::class);
        $repo1 = $this->getDoctrine()->getRepository(MesPrestationInterval::class);
        $maprestation = $repo->find($request->request->get('idmp'));


        // on recupere les deux tableaux avec les intervalles a ajouter et a supprimer
        $my_array = array();
        $my_array_delete = array();
        $tab = $request->request->get('interval');
        $tabDelete = $request->request->get('supprimer');
        $my_array=json_decode($tab,true);
        $my_array_delete = json_decode($tabDelete,true);
        $mesIntervalActuel = $maprestation->getMesPrestationIntervals();
        if (count($my_array_delete)>0){
            foreach($mesIntervalActuel as $actuelInterval){
                for ($j = 0 ; $j < count($my_array_delete);$j++){
                    if (($my_array_delete[$j][0] == $actuelInterval->getIntervalMin()) ){
                        
                        $maprestation->removeMesPrestationInterval($actuelInterval);
                        
                    }
                }
            }
            try{
            $manager->persist($maprestation);
            $manager->flush();
            } catch  (DBALException $e){
                $this->addFlash('warning','Une erreur c\'est produite, merci de verifier les informations renseignées');
                return $this->redirectToRoute('show_mes_prestation');
            }
        }

        
        
        for ($i = 0 ; $i < count($my_array);$i++){
            $intervalPrestation = new MesPrestationInterval();
            $intervalPrestation->setIntervalMin($my_array[$i][0])
                               ->setIntervalMax($my_array[$i][1])
                               ->setQuantite($my_array[$i][2])
                               ->setQuantiteNonMixte($my_array[$i][3])
                               ->setPrixUnitaire($my_array[$i][4])
                               ->setPrixUnitaireNonMixte($my_array[$i][5]);
            // si c'est la premiere ligne du tableau et que l'intervalle min est à 0
            if($i == 0 && $intervalPrestation->getIntervalMin()==0){
                if($intervalPrestation->getQuantite()==0){
                $intervalPrestation->setTauxInterval(0);

                }else{

                    $intervalPrestation->setTauxInterval($intervalPrestation->getIntervalMax()/$intervalPrestation->getQuantite());
                }
                if($intervalPrestation->getQuantiteNonMixte()==0){

                    $intervalPrestation->setTauxIntervalNonMixte(0);
                }else{
                    $intervalPrestation->setTauxIntervalNonMixte($intervalPrestation->getIntervalMax()/$intervalPrestation->getQuantiteNonMixte());

                }
                $intervalPrestation->setTauxErreur(0)
                             ->setTauxErreurNonMixte(0);





                             
            }
            
            
            // si l'intevall min n'est pas 0 on recupere l'interval précédant pour calculer les taux
            else{
                $tableInterval = $maprestation->getMesPrestationIntervals();
                // on parcours tous les intervals deja inserer pour récuperer le précedant
                foreach($tableInterval as $interval){
                    if ($interval->getIntervalMax() == $intervalPrestation->getIntervalMin()){
                        $intervalPrecedant = $interval;
                    }
                }
                // on verifie que la quantité n'est pas null pour ne pas avoir une division par 0
                // on calcul le taux pour l'interval précédent deja inserer
                if($intervalPrecedant->getQuantite()==0){
                    $tauxmin = 0;
                }else{

                    $tauxmin = ($intervalPrecedant->getIntervalMax())/($intervalPrecedant->getQuantite());
                }
                // on calcul le taux pour l'interval qu'on veux inserer
                if($intervalPrestation->getQuantite()==0){
                    $tauxmax = 0;
                }else{
                    $tauxmax = $intervalPrestation->getIntervalMax()/$intervalPrestation->getQuantite();

                }
                // on insert notre taux
                $intervalPrestation->setTauxInterval(($tauxmin+$tauxmax)/2);
                    // on refait le meme procede si non mixte
                    if($intervalPrecedant->getQuantiteNonMixte()==0){
                        $tauxminNonMixte = 0;
                    }else{
                        $tauxminNonMixte =$intervalPrecedant->getIntervalMax()/$intervalPrecedant->getQuantiteNonMixte();

                    }if($intervalPrestation->getQuantiteNonMixte()==0){
                        $tauxmaxNonMixte = 0;
                    }else{
                        $tauxmaxNonMixte= $intervalPrestation->getIntervalMax()/$intervalPrestation->getQuantiteNonMixte();
                    }

                    // on calcule le taux d'erreur pour mixte et non mixte (tauxErreur = (quantitemax - quantitemin)/2
                    $intervalPrestation->setTauxIntervalNonMixte(($tauxminNonMixte+$tauxmaxNonMixte)/2)
                             ->setTauxErreur(($intervalPrestation->getQuantite()-$intervalPrecedant->getQuantite())/2)
                             ->setTauxErreurNonMixte(($intervalPrestation->getQuantiteNonMixte()-$intervalPrecedant->getQuantiteNonMixte())/2);
            }
            try{
            $maprestation->addMesPrestationInterval($intervalPrestation);
            $manager->persist($intervalPrestation);
            $manager->flush();
            }
            catch  (DBALException $e){
                $this->addFlash('warning','Une erreur c\'est produite, merci de verifier les informations renseignées');
            }
            
        }
        $this->addFlash('success','Votre prestation a bien été enregistée.');
        return $this->redirectToRoute('show_mes_prestation');
    }

    /**
     * @Route("/admin/mes_prestation/show",name="show_mes_prestation")
     */
    public function showMesPrestations(){
        $repo = $this->getDoctrine()->getRepository(MesPrestation::class);
        $mesprestation = $repo->findAll();
        return $this->render('mes_prestation/show.html.twig',[
            'mesprestation' => $mesprestation
        ]);
    }
    /**
     * @Route("/admin/mes_prestation/{id}/delete",name="delete_mes_prestation")
     */
    public function deleteMaPrestation(EntityManagerInterface $manager,MesPrestation $maprestation){
        //try{
            $manager->remove($maprestation);
            $manager->flush();
         //   $this->addFlash('success','Votre prestation a bien été suprimée.');
        //} catch  (DBALException $e){
          //  $this->addFlash('warning','Une erreur c\'est produite, impossible de supprimer cette prestation');
       // }
        return $this->redirectToRoute('show_mes_prestation');
    }


}

event-master/templates/mes_prestation/add_interval.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <style>
        .table{
            width:60%;
        }
        #delete-row{
            color : red;
            background-color:white;
            border : none;
        }

    </style>
{% endblock %}

{% block body %}
    <script>  
      var intervalExistant = [];
      var index = 0;
      var intervalMax = [0];
    </script>
    <table class="table table-hover" id="table">
        <thead>
            <tr>
                <th scope="col">intervalle minimum</th>
                <th scope="col">intervalle maximum</th>
                <th scope="col">quantite</th>
                <th scope="col">quantite non mixte</th>
                <th scope="col">prix unitaire</th>
                <th scope="col">prix unitaire non mixte</th>
                <th></th>
            </tr>
        </thead>
        <tbody id="tbody">
            {% set index = 0 %}
            {% for inteval in maPrestation.getMesPrestationIntervals %}
              <tr id='{{ index }}'>
                <td>{{inteval.intervalMin}}</td>
                <td>{{inteval.intervalMax}}</td>
                <td>{{inteval.quantite}}</td>
                <td>{{inteval.quantiteNonMixte}}</td>
                <td>{{inteval.prixUnitaire}}</td>
                <td>{{inteval.prixUnitaireNonMixte}}</td>
                <td><button type='botton' id='delete-row' onclick='deleteRow({{ index }})'><i class='far fa-trash-alt'></i></button></td>
              </tr>
              <script>
                intervalExistant.push([{{inteval.intervalMin}},{{inteval.intervalMax}},{{inteval.quantite}},{{inteval.quantiteNonMixte}},{{inteval.prixUnitaire}},{{inteval.prixUnitaireNonMixte}}]);
                index = {{ index }};
                intervalMax.push({{inteval.intervalMax}});
              </script>
              {% set index = index + 1 %}
            {% endfor %}
    </table>

    <div class="container">
      <div class="row">
        <div class="col-md-12">

          <div class="modal fade" id="myModal">
            <div class="modal-dialog modal-12">
                <div class="modal-content">
                    <div class="modal-header">
                      <h1>Titre</h1>
                    </div>
                    <form class="form" action="index.html" method="post">
                    <div class="modal-body">
                          <div class="table-responsive">
                            <div class="input">
                                <label class="label-modal">Intervalle minimum: </label>
                              <p id="intervalle-minimum"> <p>
                            </div>
                            <div class="input">
                                <label class="label-modal">intervalle maximum: </label>
                                <input class="form-control" placeholder="intervalle maximum" name="interval-max" intervalid="interval" type="number" default="" required/>
                            </div>
                             <div class="input">
                                <label class="label-modal">quantité: </label>
                                <input class="form-control" placeholder="quantité" name="quantite" intervalid="interval" type="number" default="" required/>
                            </div>
                            <div class="input">
                                <label class="label-modal">quantité non mixte: </label>
                                <input class="form-control" placeholder="quantité" name="quantite_non_mixte" intervalid="interval" type="number" default="" required/>
                            </div>
                            <div class="input">
                                <label class="label-modal">prx unitaire: </label>
                                <input class="form-control" placeholder="prix unitaire" name="prx_unitaire" intervalid="interval" type="number"  default="" required/>
                            </div>
                            <div class="input">
                                <label class="label-modal">prx unitaire non mixte: </label>
                                <input class="form-control" placeholder="prix unitaire non mixte" name="prx_unitaire_non_mixte" intervalid="interval" type="number"  default="" required/>
                            </div>
                            
                          </div>
                     
                    </div>
                    <div class="modal-footer">
                      <button class="btn btn-danger" data-dismiss="modal" value="Close">close</button>
                      <button class="btn btn-success" type="submit" href="#" onclick="izane()" data-dismiss="modal" value="Save" id="save">Save</button>
                    </div>
                     </form>
                </div>
            </div>
          </div>
          <a href="#" data-toggle="modal" data-target="#myModal" onclick="putIntervalleMax()"> Open</a>
          <button class="btn btn-success" onclick="sendData()">Enregistrer</button>
        </div>
      </div>
    </div>

{% block javascripts %}
 <script type="text/javascript" src="{{ asset('https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js') }}"> </script>
<script src="{{ asset('https://code.jquery.com/ui/1.12.1/jquery-ui.js' ) }}"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="http://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    <script>
      var lineToAdd=[];
      var lineToDelete=[];
    //  var ligneToDelete = document.getElementById(index).cells;
     // var tabtmp =[parseInt(ligneToDelete[0].innerHTML),parseInt(ligneToDelete[1].innerHTML),parseInt(ligneToDelete[2].innerHTML),parseInt(ligneToDelete[3].innerHTML),parseInt(ligneToDelete[4].innerHTML),parseInt(ligneToDelete[5].innerHTML)];
     // console.log(tabtmp);
    //  console.log(intervalExistant);
    //  console.log(inTab(intervalExistant,tabtmp));
      var tableLength = document.getElementById("tbody").childNodes.length;
      var table = document.getElementById('tbody');
      function izane(){
          var tableauInput = document.getElementsByClassName('form-control');
          var valueNull = false;
          for (var i =0 ; i<tableauInput.length;i++){
              if(tableauInput[i].value==""){
                    valueNull =true;
                    alert(tableauInput.name + 'n\'est pas renseignée');
              }
              
          }
          if(parseInt(tableauInput[0].value<=intervalMax[intervalMax.length-1])){
            alert('l\'intervalle maximum doit etre strictement superieur à l\'intervalle minimum');
            
          }

          else if(!(valueNull)){
              tableLength = document.getElementById("tbody").childNodes.length;
            intervalMax.push(tableauInput[0].value);
            //alert(tableauInput[0]+' => '+tableauInput[1]);
            var row = table.insertRow();
            index += 1;
            row.id =  index;
            var cell1 = row.insertCell();
            var cell2 = row.insertCell();
            var cell3 = row.insertCell();
            var cell4 = row.insertCell();
            var cell5 = row.insertCell();
            var cell6 = row.insertCell();
            var cell7 = row.insertCell();
            cell1.innerHTML = intervalMax[intervalMax.length-2];
            cell2.innerHTML = tableauInput[0].value;
            cell3.innerHTML = tableauInput[1].value;
            cell4.innerHTML = tableauInput[2].value;
            cell5.innerHTML = tableauInput[3].value;
            cell6.innerHTML = tableauInput[4].value;
            cell7.innerHTML = "<button type='botton' id='delete-row' onclick='deleteRow("+row.id+")'><i class='far fa-trash-alt'></i></button>";
            lineToAdd.push([parseInt(intervalMax[intervalMax.length-2]),parseInt(tableauInput[0].value),parseInt(tableauInput[1].value),parseInt(tableauInput[2].value),parseInt(tableauInput[3].value),parseInt(tableauInput[4].value)]);
           
          }
      }

      // ici lors de la suppression d'une ligne on supprime toutes les lignes suivantes et les intervalles collectés.
      function deleteRow(x){
          allRow = table.childNodes;
          var ligneToDelete = [];
          while(index > x || index == x){
            ligneToDelete = document.getElementById(index).cells;
            tabLigneToDelete = [parseInt(ligneToDelete[0].innerHTML),parseInt(ligneToDelete[1].innerHTML),parseInt(ligneToDelete[2].innerHTML),parseInt(ligneToDelete[3].innerHTML),parseInt(ligneToDelete[4].innerHTML),parseInt(ligneToDelete[5].innerHTML)];
            if (inTab(intervalExistant,tabLigneToDelete)){
              lineToDelete.push(tabLigneToDelete);   
            }else{
            lineToAdd.pop();
            console.log(lineToAdd);
            }
            table.deleteRow(index);
              intervalMax.pop();
              index -= 1;
          }
          
      }
      // ici on recupere le champ intervalle min du modal pour le mettre à jour
      function putIntervalleMax(){
        console.log(lineToAdd);
        var p = document.getElementById("intervalle-minimum");
        p.innerHTML=intervalMax[intervalMax.length-1];
      }
      function sendData(){
        console.log(lineToDelete);
      if(lineToAdd.length > 0 || lineToDelete.length  > 0){
        $json_array = JSON.stringify(lineToAdd);
        $json_array_delete = JSON.stringify(lineToDelete);
        $.ajax({
          type: "POST",
          url: "/admin/mes_prestation/putAddedInterval",
          data:{
            "idmp": {{maPrestation.id}} , "interval" : $json_array , "supprimer" : $json_array_delete
          },
          success: function(data){
            
          },
          error : function(data){

          }
        }) ;
      }
      }

      // nous allons definir une fonction pour voir si un tableau est contenue dans un autre 
      function inTab(a,b){
        for(var i =0 ; i < a.length;i++){
          var diff = false;
          if (a[i].length == b.length){
            var j = 0;
            while((!diff) && j< b.length){
              if ( a[i][j] != b[j]){
                diff = true;
              }
              j++;
            }
            if(j == b.length){
              return true;
           }
          }
        }
       return false;
      }
    </script>
      

{% endblock %}
{% endblock %}

event-master/templates/mes_prestation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes Prestations{% endblock %}

{% block body %}





{% endblock %}

event-master/templates/mes_prestation/new.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_4_layout.html.twig'%}
{% block stylesheets %}
<style>
.custom-control-input {
 position:absolute;
 left:0;
 z-index:-1;
 width:1rem;
 height:1.25rem;
 opacity:0
}
.custom-control-input:checked ~ .custom-control-label::before {
 color:#fff;
 border-color:#fc7486;
 background-color:#fc7486
}
.custom-control-input:focus ~ .custom-control-label::before {
 -webkit-box-shadow:0 0 0 0.2rem rgba(120,194,173,0.25);
 box-shadow:0 0 0 0.2rem rgba(120,194,173,0.25)
}
.custom-control-input:focus:not(:checked) ~ .custom-control-label::before {
 border-color:#d0eae2
}
.custom-control-input:not(:disabled):active ~ .custom-control-label::before {
 color:#fff;
 background-color:#f3faf8;
 border-color:#f3faf8
}
.custom-control-input[disabled] ~ .custom-control-label,
.custom-control-input:disabled ~ .custom-control-label {
 color:#888
}
.custom-control-input[disabled] ~ .custom-control-label::before,
.custom-control-input:disabled ~ .custom-control-label::before {
 background-color:#f7f7f9
}
</style>
{% endblock %}
{% block body %}
<h1> Nouvelle préstation </h1>
    <div>
    {{form_start(form)}}
    {{form_row(form.nomPrestation)}}
    {{form_row(form.nombreEmployes)}}
    {{form_row(form.prix)}}
    {{form_row(form.DependNbInvites)}}
    <div class="form-group"><button type="submit" class="btn btn-primary">
        {% if modified %}
        modifier Ma préstation
    {% else %}
        Ajouter ma préstation </button></div>
    {% endif %} 
    {{ form_end(form)}}
    </div>
   
    <script> 
    // modifier les class pour l'adapter au theme bootstrap
    var buttonSubmit = document.getElementsByClassName('btn btn-primary');
    var textButtonSubmit = buttonSubmit[0].textContent;
  const fileSelector = document.getElementById('mes_prestation_DependNbInvites');
  const fileSelectorLabel = document.getElementsByClassName('form-check-label');
  fileSelectorLabel[0].className = 'custom-control-label';
    fileSelector.className='custom-control-input';
    fileSelector.parentNode.className = 'custom-control custom-switch';
    fileSelector.onclick = function() {
        var chebox = fileSelector;
     //   var buttonSubmit = document.getElementsByClassName('btn btn-primary');
        
        console.log(textButtonSubmit);
        
        if (chebox.checked == true){
            buttonSubmit[0].textContent = 'ajouter interval';
            //console.log(buttonSubmit[0]);
            
        } 
        
        
         else {
           buttonSubmit[0].textContent = textButtonSubmit;
  }
    };

  ;
</script>
{% endblock %}