event-master/src/Entity/Prestation.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PrestationRepository")
 */
class Prestation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nomClient;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $dateEnd;
   
    /**
     * @ORM\Column(type="integer")
     */
    private $Total;

    /**
     * @ORM\Column(type="integer")
     */
    private $acompte;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $typeTransaction;

    /**
     * @ORM\Column(type="integer")
     */
    private $resteAPayer;

    /**
     * @ORM\Column(type="integer")
     */
    private $Remise;

    /**
     * @ORM\Column(type="integer")
     */
    private $frais;

    /**
     * @ORM\Column(type="integer")
     */
    private $benefice;

    /**
     * @ORM\Column(type="integer")
     */
    private $NbInvites;
    /**
     * @ORM\Column(type="integer")
     */
    private $NbEmployes ;

    /**
     * @ORM\Column(type="integer")
     */
    private $NbEmployesAssignes;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Employes", inversedBy="PrestationsAssignees")
     * @ORM\JoinTable(name="prestation_employes")
     */
    private $EmployesAssignes;

    /**
     * @ORM\ManyToMany(targetEntity=MesPrestation::class, inversedBy="prestations")
     */
    private $PrestationsReservees;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Statut;



    private $prestationReserve = [];

    /**
     * @ORM\Column(type="boolean")
     */
    private $Mixte; 
    

    public function __construct()
    {
        $this->EmployesAssignes = new ArrayCollection();
        $this->PrestationsReservees = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomClient(): ?string
    {
        return $this->nomClient;
    }

    public function setNomClient(string $nomClient): self
    {
        $this->nomClient = $nomClient;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }



    public function getTotal(): ?int
    {
        return $this->Total;
    }

    public function setTotal(int $Total): self
    {
        $this->Total = $Total;

        return $this;
    }

    public function getAcompte(): ?int
    {
        return $this->acompte;
    }

    public function setAcompte(int $acompte): self
    {
        $this->acompte = $acompte;

        return $this;
    }

    public function getTypeTransaction(): ?string
    {
        return $this->typeTransaction;
    }

    public function setTypeTransaction(string $typeTransaction): self
    {
        $this->typeTransaction = $typeTransaction;

        return $this;
    }

    public function getResteAPayer(): ?int
    {
        return $this->resteAPayer;
    }

    public function setResteAPayer(int $resteAPayer): self
    {
        $this->resteAPayer = $resteAPayer;

        return $this;
    }

    public function getRemise(): ?int
    {
        return $this->Remise;
    }

    public function setRemise(int $Remise): self
    {
        $this->Remise = $Remise;

        return $this;
    }

    public function getFrais(): ?int
    {
        return $this->frais;
    }

    public function setFrais(int $frais): self
    {
        $this->frais = $frais;

        return $this;
    }

    public function getBenefice(): ?int
    {
        return $this->benefice;
    }

    public function setBenefice(int $benefice): self
    {
        $this->benefice = $benefice;

        return $this;
    }

    public function getNbInvites(): ?int
    {
        return $this->NbInvites;
    }

    public function setNbInvites(int $NbInvites): self
    {
        $this->NbInvites = $NbInvites;

        return $this;
    }
    public function getNbEmployes(): ?int
    {
        return $this->NbEmployes;
    }

    public function setNbEmployes(int $NbEmployes): self
    {
        $this->NbEmployes = $NbEmployes;

        return $this;
    }

    public function getNbEmployesAssignes(): ?int
    {
        return $this->NbEmployesAssignes;
    }

    public function setNbEmployesAssignes(int $NbEmployesAssignes): self
    {
        $this->NbEmployesAssignes = $NbEmployesAssignes;

        return $this;
    }

    /**
     * @return Collection|Employes[]
     */
    public function getEmployesAssignes(): Collection
    {
        return $this->EmployesAssignes;
    }

    public function addEmployesAssigne(Employes $employesAssigne): self
    {
        if (!$this->EmployesAssignes->contains($employesAssigne)) {
            $this->EmployesAssignes[] = $employesAssigne;
        }

        return $this;
    }

    public function removeEmployesAssigne(Employes $employesAssigne): self
    {
        if ($this->EmployesAssignes->contains($employesAssigne)) {
            $this->EmployesAssignes->removeElement($employesAssigne);
        }

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->dateEnd;
    }

    public function setDateEnd(?\DateTimeInterface $dateEnd): self
    {
        $this->dateEnd = $dateEnd;

        return $this;
    }

    /**
     * @return Collection|MesPrestation[]
     */
    public function getPrestationsReservees(): Collection
    {
        return $this->PrestationsReservees;
    }

    public function addPrestationsReservee(MesPrestation $prestationsReservee): self
    {
        if (!$this->PrestationsReservees->contains($prestationsReservee)) {
            $this->PrestationsReservees[] = $prestationsReservee;
        }

        return $this;
    }

    public function removePrestationsReservee(MesPrestation $prestationsReservee): self
    {
        if ($this->PrestationsReservees->contains($prestationsReservee)) {
            $this->PrestationsReservees->removeElement($prestationsReservee);
        }

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->Statut;
    }

    public function setStatut(string $Statut): self
    {
        $this->Statut = $Statut;

        return $this;
    }

    public function getPrestationReserve(): ?array
    {
        return $this->prestationReserve;
    }

    public function setPrestationReserve(array $prestationReserve): self
    {
        $this->prestationReserve = $prestationReserve;

        return $this;
    }

    public function getMixte(): ?bool
    {
        return $this->Mixte;
    }

    public function setMixte(bool $Mixte): self
    {
        $this->Mixte = $Mixte;

        return $this;
    }


    
}

event-master/src/Controller/PrestationController.php
<?php

namespace App\Controller;
use Dompdf\Dompdf;
use Dompdf\Options;
use Twig\Environment;
use App\Entity\Employes;
use function Sodium\add;
use App\Entity\Prestation;
use App\Entity\MesPrestation;
use App\Repository\EmplyesRepository;
use App\Repository\EmployesRepository;
use App\Controller\EmployesController ;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PrestationController extends AbstractController
{
    private $twig;

    public function __construct(Environment $twig)
    {
        $this->twig = $twig;
    }

    /**
     * @Route("/profile/prestation/calendar", name="prestation_calendar", methods={"GET"})
     * @Route("/admin/prestation/calendar", name="prestation_calendar", methods={"GET"})
     */
    public function calendar(): Response
    {
        
        return $this->render('prestation/calendar.html.twig');
    }


     /**
     * @Route("/admin/prestation/{id}/calendarInfo", name="prestation_calendar_info", methods={"GET"})
     */
    public function calendarInfo(): Response
    {
        return new Response($prestation);
    }



    /**
     * @Route("/admin/prestation/new", name="create_prestation")
     * @Route("/admin/prestation/{id}/edit",name="edit_prestation")
     */
    public function create(Request $request ,EntityManagerInterface $manager,prestation $Prestation=null) {
        $modified = true;
        if(!$Prestation){
            $Prestation = new Prestation();
            $modified = false;
        }
        
        $mesprestation = $this->getDoctrine()
            ->getRepository(MesPrestation::class)
            ->findAll();
            $mespres = array();
            foreach ($mesprestation as $m){
                $mespres[$m->getNomPrestation()]=$m->getNomPrestation();
            }
            
        $formPrestation = $this->createFormBuilder($Prestation)
                               ->add('nomClient',TextType::class,[
                                   'attr' => [
                                       'placeholder'=> 'Nom du client'
                                   ]
                               ])
                               ->add('adresse',TextType::class,[
                                'attr' => [
                                    'placeholder'=> 'adresse de la prestation'
                                ]
                            ])
                               ->add('date',DateType::class,array(
                                   'widget' => 'single_text'
                               ))
                               ->add('prestationReserve',ChoiceType::class,
                               ['choices' => $mespres,
                               'multiple'=>true,'expanded'=>true])
                               ->add('total', MoneyType::class, [
                                'currency' => 'DZD'
                            ])

                               -> add('NbInvites',IntegerType::class,['attr' => [
                                'placeholder'=> 'Nombre d\'invités']])

                               ->add('acompte', MoneyType::class, [
                                'currency' => 'DZD'
                            ])
                            ->add('mixte',  ChoiceType::class, [
                                'choices'  => [
                                    'Oui' => true,
                                    'Non' => false
                                    ],
                            ]
                            )
                               ->add('typeTransaction',  ChoiceType::class, [
                                'choices'  => [
                                    'cash' => 'cash',
                                    'CCP' => 'CCP',
                                    'chéque de banque' => 'chéque de banque'],
                            ])
                               ->add('remise', MoneyType::class, [
                                'currency' => 'DZD'
                            ])
                               ->add('frais', MoneyType::class, [
                                'currency' => 'DZD'
                            ])
                
                               ->getForm();

        

        $formPrestation->handleRequest($request);
        if($formPrestation->isSubmitted() && $formPrestation->isValid()){
                          $Prestation->setResteAPayer($Prestation->getTotal()-$Prestation->getAcompte())
                          ->setBenefice($Prestation->getTotal()-$Prestation->getFrais());
             
            $user = $this->getUser();
            if($user->getRoles()[0]=='ROLE_ADMIN' or $user->getRoles()=='ROLE_USER'){
                $Prestation->setStatut('validé');
            }
            else{
                $Prestation->setStatut('En cours');
            } 
            $nbEmployes=0 ;      
            $repo = $this->getDoctrine()->getRepository(MesPrestation::class);     
            for ($i =0;$i<count($Prestation->getPrestationReserve());$i++ ){
                foreach ($mesprestation as $m){
                    if($m->getNomPrestation()==$Prestation->getPrestationReserve()[$i]){
                        $Prestation->addPrestationsReservee($m);
                        $nbEmployes += $m->getNombreEmployes();
                    }
                }
            }
            $Prestation->setNbemployes($nbEmployes)
                       ->setNbEmployesAssignes(0);
            $manager->persist($Prestation);
            $manager->flush();
            return $this->redirectToRoute('show_prestation');

        }
        return $this->render('prestation/new.html.twig',['formPrestation' => $formPrestation->createView(),'modified' => $modified]);
    }
    /**
     *  @Route("/admin/prestation/show", name="show_prestation")
     */
    public function prestation(){
        $repo = $this->getDoctrine()->getRepository(Prestation::class);
        $prestations = $repo->findBy([],['date' => 'DESC']);
        
        //var_dump($prestations[0]);
        return $this->render('prestation/show.html.twig',[
            'controller_name' => 'PrestationController',
            'prestations' => $prestations
        ]);
    }
    /**
     * @Route("/admin/prestation/{id}/delete", name="delete_prestation")
     */
    public function deletePrestation(EntityManagerInterface $manager,Prestation $prestation){
        $manager->remove($prestation);
        $manager->flush();
        return $this->redirectToRoute('show_prestation');
    }

    /**
     * @Route("/admin/prestation/{id}/employes",name="employes_assignes_prestation")
     */
    public function employesAssignes(EmployesRepository $repo,Prestation $prestation,EntityManagerInterface $manager){

       $employesAssignes =  $repo->getEmployesAssigne($prestation);
 

        $employesNonAssignes = $repo->getEmployesNonAssigne($prestation);

    
        
        

        return $this->render('prestation/employesAssignes.html.twig',[

            'prestation' => $prestation,
            'employesNonAssignes' => $employesNonAssignes,
            'employesAssignes' => $employesAssignes

        ]);

    }
       /**
     * @Route("/admin/prestation/assigner",name="prestation_assigner", methods={"POST"})
     */
    public function assignerEmploye(Request $request,EntityManagerInterface $manager ){
        
        //$controller = $this->get('conntrollerEmployes');
        //$rep = $this->forward('App\Controller\EmployesController::employe') ;
        //$employe = $controller->employe();
        $my_array = array();
        $tab = $request->request->get('ide');
        $my_array = json_decode($tab,true);
        $repo = $this->getDoctrine()->getRepository(Employes::class);
        $repo1 = $this->getDoctrine()->getRepository(Prestation::class);
        $prestation = $repo1->find($request->request->get('idp'));

        foreach ($my_array as $value){
            $employe = $repo->find($value);
            $prestation = $prestation->addEmployesAssigne($employe);
            $employe = $employe->addPrestationsAssignee($prestation);
            $manager->flush();
        }
        
        
        return $this->redirectToRoute('prestation_index',["id" => $prestation->getId()]);



    }
    /**
     * @Route("/admin/prestation/retirer",name="prestation_retirer", methods={"POST"})
     */
    public function retirerAssigne(Request $request,EntityManagerInterface $manager){
        $my_array = array();
        $tab = $request->request->get('ide');
        $my_array = json_decode($tab,true);
        $repo = $this->getDoctrine()->getRepository(Employes::class);
        $repo1 = $this->getDoctrine()->getRepository(Prestation::class);
        $prestation = $repo1->find($request->request->get('idp'));
        foreach ($my_array as $value){
        $employe = $repo->find($value);
        $prestation = $prestation->removeEmployesAssigne($employe);
        $employe = $employe->removePrestationsAssignee($prestation);
        $manager->flush();
        }
        return $this->redirectToRoute('prestation_index',["id" => $prestation->getId()]);

    }

    



    /**
     * @Route("/admin/prestation/{id}/details",name="details_prestation")
     */
    public function imprimer(Prestation $prestation,EntityManagerInterface $manager){

         $pdfOptions = new Options();
         $pdfOptions->set('defaultFont', 'Arial');
         
        
         $dompdf = new Dompdf($pdfOptions);
         

event-master/templates/prestation/details.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        
        
        <link rel="stylesheet" href="https://bootswatch.com/4/minty/bootstrap.min.css">
       
        {% block stylesheets %}
        
        {% endblock %}
    </head>

{% block title %}Details de la prestation {% endblock %}

{% block body %}

 
    

     
    <h4>{{"Nom du client : " ~  prestation.nomClient}}</h4>
    <h4>{{"Adresse de la prestation : " ~ prestation.adresse}}</h4>
    <h4>{{ "Date de la prestation : " ~ prestation.date | date('Y/m/d')}}</h4>
    
    {% set result = '' %}
    {% for maPrestation in prestation.prestationReserve %}
      {% set result = result ~ maPrestation ~ ', ' %} 
    {% endfor %}
    <h4>
    {{ " Prestataions reservées  : " ~ result}}
    </h4>
    <h4>{{"Nombre d'invités  : " ~ prestation.nbInvites}}</h4>
    <h4>{{"Nombre d'employés  : " ~ prestation.nbEmployes}}</h4>
    <h4>{{"Nombre d'employés assignés  : " ~ prestation.NbEmployesAssignes}}</h4>
    <h4>{{"Accompte  : " ~ prestation.acompte}}</h4>
    <h4>{{"Reste a payer  : " ~ prestation.resteAPayer}}</h4>
    <h4>{{"Remise  : " ~ prestation.remise}}</h4>
    <h4>{{"Frais : " ~ prestation.frais}}</h4>
    <h4>{{"Total  : " ~ prestation.total}}</h4>
    
       
       
        
{% endblock %}
</html>

event-master/templates/prestation/employesAssignes.html.twig
{% extends 'base.html.twig' %}


{% block head %}
{% endblock %}
{% block body %}
<h1> employes assignés à cette prestation </h1>
{% for message in app.flashes('success') %}
<div class="alert alert-success">
  {{ message }}
</div>
{% endfor %}



<table id="table_a" class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Nom </th>
      <th scope="col">Prénom </th>
      <th scope="col">poste </th>

      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for employe in employesAssignes %}
    <tr id="{{employe.id}}" class="table-light">

      <td id="name" >{{employe.nom}}</td>
      <td id="prenom">{{employe.prenom}}</td>
      <td id="typePost">{{employe.typePost}}</td>
      <td id="button"><button type="button" onclick="handlerRemoveEmploy(this)" class="retirer" id="retirer"
          value="{{employe.id}}">retirer </button></td>

    </tr>

    {% endfor %}
  </tbody>
  <tfoot>
    <tr>
      
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        <button id="add" type="button" class="btn btn-secondary disabled"> ajouter </button>

        <button id='saves' type="button" class="btn btn-secondary disabled" onclick="sendData()"> save </button>
      </td>

    </tr>
  </tfoot>
</table>

<div id="user_dialog" titre="add Data">

  <table id ='table_b' class="table table-hover">
    <thead>
      <tr>
        <th></th>
        <th>nom</th>
        <th> prenom</th>
        <th>poste </th>
      </tr>
    </thead>
    <tbody>

      {% for empl in employesNonAssignes %}
      <tr id="{{empl.id}}" onclick="handlerEmployAssin(this)">
        <td> </td>
        <td id="name">{{ empl.nom  }} </td>
        <td id="prenom"> {{ empl.prenom  }}</td>
        <td id="typePost"> {{ empl.typePost  }} </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <button  type="button" class="btn btn-secondary disabled"> save </button>
</div>
{% block javascripts %}
<script type="text/javascript"
  src="{{ asset('https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js') }}"> </script>
<script src="{{ asset('https://code.jquery.com/ui/1.12.1/jquery-ui.js' ) }}"></script>
<script type="text/javascript">

  
  var tab_copy = [] ;

  var tab = [];
  $att = '';
  tab_removed = [];
  tab_final = [] ;
  function removeElement(array, elem) {
    var index = array.indexOf(elem);
    if (index > -1) {
        array.splice(index, 1);
    }
}

  function handlerEmployAssin(employeCell) {
    const idEmploye = employeCell.getAttribute('id');
    const employe = { name: "", id: idEmploye, prenom: "", typePost: "" }
    let arrayOfSelectedEmploye = employeCell.querySelectorAll('td');
    tab.push(idEmploye);
    for (const employTd of arrayOfSelectedEmploye) {
      if (!!employTd.getAttribute('id')) {
        const nameOfKey = employTd.getAttribute('id');
        const valueOfKey = employTd.innerText;
        employe[nameOfKey] = valueOfKey;
      }
    }
    const affectEmploy = `<tr id="${idEmploye}" class="table-light">
   <td id="name">${employe.name}</td>
   <td id="prenom">${employe.prenom}</td>
   <td id="typePost">${employe.typePost}</td>
   <td><button type="button" class="retirer" id="retirer" onclick="handlerRemoveEmploy(this)" value="${idEmploye}"> retirer </button></td>
 </tr>`;
    $('#table_a tbody').append(affectEmploy);
    $('#table_b tr#'+idEmploye).remove();
}
  $(document).ready(function () {
    $('#user_dialog').dialog({
      autoOpen: false
    });
    $('#add').click(function () {
      $('#user_dialog').dialog('option', 'title', 'ajouter employé');
      $('#user_dialog').dialog('open');
    })
    $('#save').click(function () {
      $('#user_dialog').dialog();
                     
                      
    })
 
 

})

 

  function handlerRemoveEmploy(employToRemove) {
    var text = '<tr id =' + employToRemove.value +' onclick="handlerEmployAssin(this)" >';
    tab_removed.push(employToRemove.value);
    const trAssociateToEmploy = document.getElementById(employToRemove.value);
    let arrayOfTd = trAssociateToEmploy.querySelectorAll('td');
    for (const employTds of arrayOfTd) {
      if (employTds.getAttribute('id')!="button") {
            if (employTds.getAttribute('id')=="typePost"){
              
              
              text += '<td id="typePost">'+ employTds.innerText +'</td>';
            }
            else if (employTds.getAttribute('id')=="name"){
              text+= '<td id="name">'+ employTds.innerText + '</td>';
            }
            else if (employTds.getAttribute('id')=="prenom"){
             text+= '<td id="prenom">' + employTds.innerText + '</td>';
            }}}
    text += '</tr>';
    
    trAssociateToEmploy.parentNode.removeChild(trAssociateToEmploy);
    $('#table_b tbody').append(text);
    
    //alert(tab_removed);
  
  }

  
  function sendData(){
    tab_final.length = 0 ;
    for( let j = 0 ; j< tab.length ; j++ ){
        tab_copy[j]= tab[j];
    }
    for( let i = 0 ; i< tab_removed.length ; i++ ){
      if ( tab_copy.includes(tab_removed[i])){
          removeElement(tab_copy,tab_removed[i]);  
      }
    else {
      tab_final.push(tab_removed[i]);
    }
    }
    $json_array = JSON.stringify(tab_copy);
    $json_array2 = JSON.stringify(tab_final);

    if (tab_final.length != 0 ){
    $.ajax({
         type: "POST",
       url : "/admin/prestation/retirer",
      data:{
      "idp": {{prestation.id}} , "ide": $json_array2
      },
      success: function(data){
      
      },
      error : function(){
  
      }
    });
  }
     if (tab_copy.length != 0 ){
      $.ajax({
        type: "POST",
        url: "/admin/prestation/assigner",
        data: {
          "idp": {{ prestation.id }}, "ide" : $json_array
                        },
    success: function (data) {
      location.reload();
    },
    error: function () {
      // show alert or something
    } 
  
      });
  
    }
  
  
  }
  


 


</script>

{% endblock %}
{% endblock %}

event-master/templates/prestation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PrestationController!{% endblock %}

{% block body %}
 <table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Nom </th>
      <th scope="col">Prénom </th>
      <th scope="col">poste  </th>
      
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  {% for employe in employes %}
    <tr class="table-light">
      <td>{{employe.id}}</td>  
      <td>{{employe.nom}}</td>
      <td>{{employe.prenom}}</td>
      <td>{{employe.typePost}}</td>

    </tr>

    {% endfor %}
    </tbody>
    </table>
{% endblock %}

event-master/templates/prestation/new.html.twig
{% extends 'base.html.twig' %}
{% form_theme formPrestation 'bootstrap_4_layout.html.twig'%}


{% block body %}
<h1> Nouvelle prestation </h1>
    {{form_start(formPrestation)}}
    {{ form_widget(formPrestation) }}
    <div class="form-group"><button type="submit" class="btn btn-primary">
     {% if modified %}
        modifier prestation
    {% else %}
        Ajouter prestation </button></div>
    {% endif %} 
    
    {{ form_end(formPrestation) }}
{% endblock %}

event-master/templates/prestation/show.html.twig
{% extends 'base.html.twig' %}




{% block body %}
<h1> Presentation des prestations </h1>
{% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
            {% endfor %}
    <table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Nom du client</th>
      <th scope="col">adresse </th>
      <th scope="col">date </th>
      <th scope="col">prestations résérvées</th>
      <th scope="col">Invités </th>
      <th scope="col">Employes</th>
      <th scope="col">acompte</th>
      <th scope="col">reste à payer</th>
      <th scope="col">remise</th>
      <th scope="col">frais divers</th>
      <th scope="col">Totel prestation</th>
      <th scope="col">Nombre d'Employes assignés</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  {% for prestation in prestations %}
    <tr class="table-light">
     
      <td>{{prestation.nomClient}}</td>
      <td>{{prestation.adresse}}</td>
      <td>{{prestation.date | date('Y/m/d')}}</td>
      
      {% set result = '' %}
      {% for maPrestation in prestation.PrestationsReservees %}
        {% set result = result ~ maPrestation.nomPrestation ~ ', ' %} 
      {% endfor %}
      <td>
      {{result}}
      </td>
      <td>{{prestation.nbInvites}}</td>
      <td>{{prestation.nbEmployes}}</td>
      <td>{{prestation.acompte}}</td>
      <td>{{prestation.resteAPayer}}</td>
      <td>{{prestation.remise}}</td>
      <td>{{prestation.frais}}</td>
      <td>{{prestation.total}}</td>
      <td>{{prestation.NbEmployesAssignes}}<td>
      <td><button type="button" class="btn btn-secondary disabled"><a href={{path('edit_prestation', {'id': prestation.id})}} style="color:white">modifier </a> </button></td>
      <td><button type="button" class="btn btn-secondary disabled"><a href={{path('delete_prestation', {'id': prestation.id})}} style="color:white" onclick="return confirm('are u sure?')" >supprimer </a> </button></td>
      <td><button type="button" class="btn btn-secondary disabled"><a href={{path('employes_assignes_prestation', {'id': prestation.id})}} style="color:white">assigner des Employes </a> </button></td>
      <td><button type="button" class="btn btn-secondary disabled"><a href={{path('details_prestation', {'id': prestation.id})}} style="color:white">imprimer </a> </button></td>
    </tr>

    {% endfor %}
    </tbody>
    </table>
{% endblock %}